# TF Fundamentals

In [4]:
#| hide
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # 0 = all messages are logged (default behavior), 1 = INFO messages are not printed, 2 = INFO and WARNING messages are not printed, 3 = INFO, WARNING, and ERROR messages are not printed
 
print(tf.__version__)


2.15.0


In [6]:
scalar = tf.constant(9)
scalar.numpy()

9

In [3]:
scalar.ndim

0

### Creating Tensors with tf.constant()

tf.constant(
    value, dtype=None, shape=None, name='Const'
) -> Union[tf.Operation, ops._EagerTensorBase]

=> dtype helps to define the data type of the tensor - int64, float16 etc

In [4]:
vector = tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
vector.ndim

1

In [7]:
matrix = tf.constant([[1,2,3],
                      [5,8,9]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 8, 9]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([
    [[1,2,3,9],
     [4,5,6,4]],
    [[2,5,3,4],
     [4,5,8,7]],
    [[9,6,4,2],
     [3,1,2,1]]
])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 9],
        [4, 5, 6, 4]],

       [[2, 5, 3, 4],
        [4, 5, 8, 7]],

       [[9, 6, 4, 2],
        [3, 1, 2, 1]]], dtype=int32)>

In [10]:
tensor.ndim

3

### Creating Tensors with tf.variable()

tf.Variable(
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
)


A variable maintains shared, persistent state manipulated by a program.

The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

In [14]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([5,9])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 9], dtype=int32)>)

#### We can modify the elements of tensor using assign method

In [15]:
changeable_tensor[0].assign(6)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([6, 7], dtype=int32)>

In [16]:
unchangeable_tensor[0].assign(4)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating Random Tensors 

=> Majorly used for the creation of tensors for weight initialization

In [17]:
random_1 = tf.random.Generator.from_seed(16) # set seed for reproducibility
random_1

In [18]:
random_1 =random_1.normal(shape= (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.63509274,  0.3703566 ],
       [-1.0939722 , -0.46014452],
       [ 1.5420506 , -0.16822556]], dtype=float32)>

In [19]:
random_2  = tf.random.Generator.from_seed(16).normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.63509274,  0.3703566 ],
       [-1.0939722 , -0.46014452],
       [ 1.5420506 , -0.16822556]], dtype=float32)>

In [22]:
random_3  = tf.random.normal(shape = (3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.5297089 ,  2.407835  ],
       [-0.43932903, -0.14928319],
       [ 0.77528226, -2.1867003 ]], dtype=float32)>

The tf.random.Generator class
The tf.random.Generator class is used in cases where you want each RNG call to produce different results. It maintains an internal state (managed by a tf.Variable object) which will be updated every time random numbers are generated. Because the state is managed by tf.Variable, it enjoys all facilities provided by tf.Variable such as easy checkpointing, automatic control-dependency and thread safety.

There are multiple ways to create a generator object. The easiest is Generator.from_seed, as shown above, that creates a generator from a seed. A seed is any non-negative integer. from_seed also takes an optional argument alg which is the RNG algorithm that will be used by this generator:


In [24]:
g1 = tf.random.Generator.from_seed(16, alg = 'philox')
g1 = g1.normal(shape=(3,4))
g1 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.63509274,  0.3703566 , -1.0939722 , -0.46014452],
       [ 1.5420506 , -0.16822556, -0.43908644, -0.41292423],
       [ 0.35877243, -1.9095894 , -0.20947689,  0.8286217 ]],
      dtype=float32)>

### Shuffle the order of tensors

tf.random.shuffle(
    value, seed=None, name=None
)

Randomly shuffles a tensor along its first dimension.

In [27]:
not_shuffled = tf.constant([[2,5,],
                            [5,7],
                            [9,3]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [5, 7],
       [9, 3]], dtype=int32)>

In [28]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 7],
       [9, 3],
       [2, 5]], dtype=int32)>

Sets the global random seed.

tf.random.set_seed(
    seed
)

Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.

Its interactions with operation-level seeds is as follows:

If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [40]:
tf.random.set_seed(24)
tf.random.shuffle(not_shuffled, seed=24)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 3],
       [2, 5],
       [5, 7]], dtype=int32)>

### Other ways to make tensors

In [41]:
# Create tensor of all ones

tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [42]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU computing

In [44]:
# convert numpy arrays into tensors
import numpy as np 

numpy_array = np.arange(1,25, dtype=np.int16)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [49]:
constant_tf = tf.constant(numpy_array, shape = (2,3,4))
constant_tf

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [51]:
variable_tf = tf.Variable(numpy_array)
variable_tf

<tf.Variable 'Variable:0' shape=(24,) dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

### Tensor attributes - to get more information from Tensors

Shape               =>  tensor.shape

Rank                =>  tensor.ndim

Axis or Dimension   =>  tensor[0], tensor[:,1]...

Size                =>  tf.size(tensor)

In [52]:
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [53]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [54]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [58]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("shape of tensor:", rank_4_tensor.shape)
print("Elements along the zero axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("total number of elements in tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
shape of tensor: (2, 3, 4, 5)
Elements along the zero axis: 2
Elements along the last axis: 5
total number of elements in tensor: 120


### Indexing and Expanding Tensors

In [61]:
# fetching first two elements of the tensor in all dimensions

rank_4_tensor[:1,:2,:1,:3]

<tf.Tensor: shape=(1, 2, 1, 3), dtype=float32, numpy=
array([[[[0., 0., 0.]],

        [[0., 0., 0.]]]], dtype=float32)>

In [64]:
rank_2_tensor = tf.reshape(rank_4_tensor, shape=(12,10))
rank_2_tensor

<tf.Tensor: shape=(12, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [65]:
# Add Extra Dimension to any tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(12, 10, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.

In [71]:
# Alternative to tf.newaxis - expanding axis in between

changed_tensor_new = tf.expand_dims(rank_2_tensor, axis = 1)
changed_tensor_new.shape

TensorShape([12, 1, 10])

### Tensor Operations

Basic operations '+', '-', '*', '/'

In [75]:
tensor = tf.constant([[10,7],[4,9]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  9]], dtype=int32)>

In [74]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [14, 19]], dtype=int32)>

In [76]:
tensor-1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [3, 8]], dtype=int32)>

In [78]:
tensor*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 8, 18]], dtype=int32)>

In [79]:
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [2. , 4.5]])>

In [81]:
# this might speed up operations when used with GPU
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 40,  90]], dtype=int32)>

### Matrix Multiplication

In [82]:
# Dot product or Matrix multiplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 133],
       [ 76, 109]], dtype=int32)>

In [84]:
# Elementwise Multiplication
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 16,  81]], dtype=int32)>

In [85]:
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 133],
       [ 76, 109]], dtype=int32)>

In [88]:
tf.tensordot(tensor, tensor, axes =1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[128, 133],
       [ 76, 109]], dtype=int32)>

### Changing Data type in Tensors

In [89]:
A = tf.constant([[10,7],
                [5,2]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  2]], dtype=int32)>

In [90]:
B = tf.cast(A, dtype=tf.float16)
B

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 5.,  2.]], dtype=float16)>

### Aggregations

In [92]:
sample_tensor = tf.constant([[5,8],
                             [-6,9]])
sample_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  8],
       [-6,  9]], dtype=int32)>

In [96]:
tf.abs(sample_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 8],
       [6, 9]], dtype=int32)>

In [98]:
tf.reduce_sum(sample_tensor).numpy()

16

In [99]:
tf.reduce_sum(tf.abs(sample_tensor)).numpy()

28

In [100]:
tf.reduce_mean(sample_tensor).numpy()

4

In [105]:
tf.reduce_min(sample_tensor).numpy()

-6

In [107]:
tf.reduce_max(sample_tensor).numpy()

9

In [114]:
std_tensor = tf.constant([[5,8],
                             [-6,9]], dtype=tf.float32)
std_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5.,  8.],
       [-6.,  9.]], dtype=float32)>

In [115]:
std_dev = tf.math.reduce_std(std_tensor)
std_dev.numpy()

5.9581876

In [119]:
var = tf.math.reduce_variance(std_tensor).numpy()
var

35.5

### Positional Minimum and Maximum - argmin, argmax

In [125]:
#create a tensor
pos_tensor = tf.random.Generator.from_seed(16).uniform(shape=[10])
pos_tensor

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.7631861 , 0.8340243 , 0.49447727, 0.6866319 , 0.300259  ,
       0.26729417, 0.83389175, 0.62988555, 0.15143108, 0.47044265],
      dtype=float32)>

In [131]:
tf.argmax(pos_tensor).numpy()

1

In [134]:
pos_tensor[tf.argmax(pos_tensor)].numpy()

0.8340243

In [128]:
tf.argmin(pos_tensor).numpy()

8

In [133]:
pos_tensor[tf.argmin(pos_tensor)].numpy()

0.15143108

### Squeezing tensor

In [135]:
sparse_tensor = tf.random.normal(shape=(1,1,1,1,50), dtype=tf.float32)
sparse_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[ 2.665353  , -0.01305245,  3.2121453 ,  1.2325953 ,
            1.3019717 , -0.01629734, -0.66601795, -1.0432147 ,
           -1.7616948 , -1.6414421 ,  0.16661839, -0.99732476,
            0.8872941 , -1.8125703 ,  0.0966946 , -0.2159489 ,
            2.066713  ,  1.6013973 ,  0.48526224,  1.452654  ,
            1.6297206 ,  0.8971428 ,  1.1796947 ,  0.95481825,
            0.8847263 , -0.34303787,  0.86872697, -1.7373002 ,
            0.16618411,  0.40596476,  0.73277277, -1.8712598 ,
           -1.9836899 , -0.7865413 , -0.10133116,  0.47296703,
           -0.06624011, -0.18455192,  0.6794147 ,  1.4783307 ,
           -0.3054982 ,  0.96321213,  1.165348  , -1.5266519 ,
           -0.17529055,  0.9577717 , -0.12913266,  1.0376912 ,
           -1.1671338 ,  1.298102  ]]]]], dtype=float32)>

In [136]:
squeezed_tensor = tf.squeeze(sparse_tensor)
squeezed_tensor, squeezed_tensor.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([ 2.665353  , -0.01305245,  3.2121453 ,  1.2325953 ,  1.3019717 ,
        -0.01629734, -0.66601795, -1.0432147 , -1.7616948 , -1.6414421 ,
         0.16661839, -0.99732476,  0.8872941 , -1.8125703 ,  0.0966946 ,
        -0.2159489 ,  2.066713  ,  1.6013973 ,  0.48526224,  1.452654  ,
         1.6297206 ,  0.8971428 ,  1.1796947 ,  0.95481825,  0.8847263 ,
        -0.34303787,  0.86872697, -1.7373002 ,  0.16618411,  0.40596476,
         0.73277277, -1.8712598 , -1.9836899 , -0.7865413 , -0.10133116,
         0.47296703, -0.06624011, -0.18455192,  0.6794147 ,  1.4783307 ,
        -0.3054982 ,  0.96321213,  1.165348  , -1.5266519 , -0.17529055,
         0.9577717 , -0.12913266,  1.0376912 , -1.1671338 ,  1.298102  ],
       dtype=float32)>,
 TensorShape([50]))

#### One hot encoding tensor

In [137]:
some_list = [1,2,3,4]

tf.one_hot(some_list, depth =4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [139]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

In [140]:
!nvidia-smi

Sun Feb 18 02:18:32 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000               Off | 00000000:41:00.0 Off |                  Off |
| 30%   37C    P8               7W / 300W |  47144MiB / 49140MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--